name: 'Thank You Action'
description: 'An Github Action that thanks Peoples '
branding:
  icon: 'award'
  color: 'red'
author: 'Wuemeli'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true
  message:
    description: 'Message that gets sent to new pull requests or Issues'
    default: 'Thank you for submitting! We will try to review this as soon as we can.'
  searchTerm:
    description: 'Term that gets search for the Tenor API'
    default: 'thank you'

runs:
  using: 'node12'
  main: 'dist/index.js'
